I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 59, in script
    e "You've created a new Ren'Py game."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 59, in script
    e "You've created a new Ren'Py game."
  File "C:\Users\Kristen\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Kristen\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
HallmarkVN 1.0
Wed Nov 30 20:32:35 2022
